name = "Barierblock"
author = "lon21 & michalalek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "608c109af41dbb95b425820d87f1ec2380a2c5b909b9a03f949fc59e4ff409b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
