name = "Barierblock"
author = "lon21 & michalalek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a4e69ac06aebcd551a3511ba5a646d0cf5e9e8e9f4f30b1b09d15ebf6f5d542"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
