name = "Barierblock"
author = "lon21 & michalalek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3af9c29b1a9a3de961405f87aec899060f87fc4ce6f89831583b2b8494128766"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
